[phases.setup]
nixPkgs = ['dotnet-sdk_8', 'dotnet-runtime_8']

[phases.install]
cmds = ['dotnet restore']

[phases.build]
cmds = ['dotnet publish -c Release -o out --no-restore']

[phases.start]
cmd = 'dotnet out/HabitosApp.dll'

[variables]
DOTNET_ROOT = '/nix/store/*-dotnet-sdk-8*/share/dotnet'